# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_main.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../nbs/00_main.ipynb 3
def say_hello(to):
    "say hello to somebody"
    return f'Hello {to}'
